name: First Workflow
on: [push, workflow_dispatch]
jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist